# Generated by Django 3.2.13 on 2022-05-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unique number')),
                ('ID_question', models.IntegerField(unique=True, verbose_name='ID of question')),
                ('question_text', models.CharField(max_length=1000, verbose_name='Text of question')),
                ('response', models.CharField(max_length=1000, verbose_name='Text of response')),
                ('date_request', models.CharField(max_length=1000, verbose_name='Date of create question')),
            ],
        ),
    ]
