# Generated by Django 3.2.13 on 2022-05-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='response',
        ),
        migrations.AddField(
            model_name='question',
            name='response_text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Text of response'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_request',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Date of create question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Text of question'),
        ),
    ]
